spring.application.name=splity

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/splity_db
spring.datasource.username=adityakumar
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

jwt.secret=your-secret-key-here

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Upload Folder
spring.web.resources.static-locations=classpath:/static/,file:uploads/

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB