package com.rkind.splity.splityai.handler;

import com.rkind.splity.splityai.dto.request.DashboardChatRequest;
import com.rkind.splity.splityai.dto.response.DashboardChatResponse;
import com.rkind.splity.splityai.entity.AIConversation;
import com.rkind.splity.splityai.enums.SplityIntent;
import com.rkind.splity.splityai.provider.DashboardContextProvider;
import com.rkind.splity.splityai.service.AIConversationPersistenceService;
import com.rkind.splity.splityai.service.AIGeminiService;
import com.rkind.splity.splityai.util.AIResponseFormatter;
import com.rkind.splity.splityai.util.PromptBuilder;
import com.rkind.splity.splityai.model.AITokenUsage;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.util.Arrays;
import java.util.Base64;

@Component
public class GeminiHandler implements AIHandler {

    private final AIGeminiService aiGeminiService;
    private final AIConversationPersistenceService conversationPersistenceService;
    private final DashboardContextProvider contextProvider;
    private final PromptBuilder promptBuilder;
    private final AIResponseFormatter responseFormatter;

    public GeminiHandler(
            AIGeminiService aiGeminiService,
            AIConversationPersistenceService conversationPersistenceService,
            DashboardContextProvider contextProvider,
            PromptBuilder promptBuilder,
            AIResponseFormatter responseFormatter
    ) {
        this.aiGeminiService = aiGeminiService;
        this.conversationPersistenceService = conversationPersistenceService;
        this.contextProvider = contextProvider;
        this.promptBuilder = promptBuilder;
        this.responseFormatter = responseFormatter;
    }

    @Override
    public DashboardChatResponse handle(DashboardChatRequest request) {

        AIConversation conversation;

        if (request.getConversationId() == null ||
                request.getConversationId().trim().isEmpty()) {

            conversation = conversationPersistenceService.createConversation(
                    request.getUserId()
            );

            request.setConversationId(conversation.getConversationId());

        } else {

            conversation = conversationPersistenceService.getConversation(
                    request.getConversationId()
            );

            if (conversation == null) {

                conversation = conversationPersistenceService.createConversation(
                        request.getUserId()
                );

                request.setConversationId(conversation.getConversationId());
            }
        }

        conversationPersistenceService.saveUserMessage(
                request.getConversationId(),
                request.getUserId(),
                request.getMessage(),
                "GENERAL_CHAT"
        );

        String history = conversationPersistenceService
                .getConversationMessages(request.getConversationId())
                .stream()
                .map(message -> message.getRole() + ": " + message.getMessage())
                .reduce("", (a, b) -> a + b + "\n");

        String context =
                contextProvider.buildContext(
                        request.getUserId()
                );

        String prompt =
                promptBuilder.buildPrompt(
                        request,
                        history,
                        context
                );

        var aiResponse =
                aiGeminiService.generateResponse(prompt);

        String aiReply =
                responseFormatter.format(aiResponse.getReply());

        conversationPersistenceService.saveAIMessage(
                request.getConversationId(),
                request.getUserId(),
                aiReply,
                "GENERAL_CHAT",
                aiResponse.getPromptTokens(),
                aiResponse.getCompletionTokens(),
                aiResponse.getTotalTokens(),
                aiResponse.getResponseTime(),
                aiResponse.getModel(),
                false,
                1.0,
                "Generated by Gemini"
        );

        DashboardChatResponse response =
                new DashboardChatResponse();

        response.setSuccess(true);
        response.setConversationId(request.getConversationId());
        response.setReply(aiReply);
        response.setIntent(SplityIntent.GENERAL_CHAT);

        AITokenUsage tokenUsage = new AITokenUsage();

        tokenUsage.setPromptTokens(
                aiResponse.getPromptTokens()
        );

        tokenUsage.setCompletionTokens(
                aiResponse.getCompletionTokens()
        );

        tokenUsage.setTotalTokens(
                aiResponse.getTotalTokens()
        );


        response.setSuggestions(
                Arrays.asList(
                        "Wallet",
                        "Split Expenses",
                        "Travel",
                        "Help"
                )
        );

        response.setTokenUsage(tokenUsage);

        return response;
    }

    public DashboardChatResponse processImage(
            Long userId,
            String conversationId,
            MultipartFile image,
            String message
    ) {

        try {

            AIConversation conversation;

            if (conversationId == null || conversationId.isBlank()) {

                conversation = conversationPersistenceService.createConversation(userId);
                conversationId = conversation.getConversationId();

            } else {

                conversation = conversationPersistenceService.getConversation(conversationId);

                if (conversation == null) {
                    conversation = conversationPersistenceService.createConversation(userId);
                    conversationId = conversation.getConversationId();
                }
            }

            String prompt;

            if (message == null || message.isBlank()) {

                prompt = """
            You are Splity AI.

            Analyze this image carefully.

            If it is:
            - A bill or receipt -> Extract merchant, items, total amount, taxes and suggest expense splitting.
            - A QR code -> Explain what it contains.
            - A travel ticket -> Extract travel details.
            - A food bill -> Suggest equal split and custom split options.
            - A document -> Summarize it.
            - Any other image -> Describe it accurately.

            Respond in a clean, user-friendly format.
            """;

            } else {

                prompt = message;
            }

            String base64 =
                    Base64.getEncoder().encodeToString(image.getBytes());

            var aiResponse = aiGeminiService.generateImageResponse(
                    prompt,
                    base64,
                    image.getContentType()
            );

            String reply =
                    responseFormatter.format(aiResponse.getReply());

            conversationPersistenceService.saveUserMessage(
                    conversationId,
                    userId,
                    (message == null || message.isBlank())
                            ? "[IMAGE]"
                            : "[IMAGE] " + message,
                    "IMAGE"
            );

            conversationPersistenceService.saveAIMessage(
                    conversationId,
                    userId,
                    reply,
                    "IMAGE",
                    aiResponse.getPromptTokens(),
                    aiResponse.getCompletionTokens(),
                    aiResponse.getTotalTokens(),
                    aiResponse.getResponseTime(),
                    aiResponse.getModel(),
                    false,
                    1.0,
                    "Gemini Vision"
            );

            DashboardChatResponse response = new DashboardChatResponse();

            AITokenUsage tokenUsage = new AITokenUsage();

            tokenUsage.setPromptTokens(aiResponse.getPromptTokens());
            tokenUsage.setCompletionTokens(aiResponse.getCompletionTokens());
            tokenUsage.setTotalTokens(aiResponse.getTotalTokens());

            response.setTokenUsage(tokenUsage);

            response.setSuccess(true);
            response.setConversationId(conversationId);
            response.setReply(reply);
            response.setSuggestions(
                    Arrays.asList(
                            "Split this bill",
                            "Summarize",
                            "Extract text",
                            "Ask another question"
                    )
            );
            response.setIntent(SplityIntent.IMAGE_ANALYSIS);

            return response;

        } catch (Exception e) {

            e.printStackTrace();

            DashboardChatResponse response =
                    new DashboardChatResponse();

            response.setSuccess(false);
            response.setReply(e.getMessage());

            return response;
        }
    }

}